# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['board.c']
src	+= ['jh7110.c']
src	+= ['gpio.c']

CPPPATH = [cwd]

if GetDepend('BSP_USING_VF2'):
    src += ['board_vf2.c']

if GetDepend('BSP_USING_DEVKITS'):
    src += ['board_vf2.c']
    src += ['board_devkits.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
