# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

if GetDepend('BSP_USING_GMAC'):
     objs = objs + SConscript(os.path.join('gmac', 'SConscript'))

Return('objs')
